# ä¸»è¨­å®š
favicon: ğŸ®
title: yoyo's blog
subtitle: ''
description: ''
keywords: JavaScript, Vue, Front-end
author: Yoyo
language: en
timezone: ''

# URL è¨­å®š
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# è³‡æ–™å¤¾
source_dir: source # é–‹ç™¼ä¸­
public_dir: public # ç·¨è­¯å¾Œ
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# ç·¨è¼¯ï¼ˆæ’°å¯«æ–‡ç« ï¼‰
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''

filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  prismjs:
  preprocess: true

# default_category
default_category: uncategorized
category_map: 
tag_map: 

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Themes
theme: aomori

# åŒ…å« & æ’é™¤
include:
exclude:
ignore:

# é¦–é è¨­å®š
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# å¥—ä»¶è¨­å®š

# Menu
aomori_menu:
  Home: /
  Archives: /archives
  About: /about

aomori_widgets:
  - toc
  - category 
  - tag
  - archive

aomori_copyright: false